### ISSUE TITLE
Option to select display units.

### ISSUE THREAD

**Issue by marcusdoesstuff** [Microsoft/powerbi-visuals-sankey#10]
An option to be able to select the display units would be very helpful. Currently it looks automatic. If one bar is £4000 it comes up as £4.00k... Unfortunately that means a bar with a value of £3 shows as £0.00k
Thanks. :)

**Comment by vipinmenontp** [comment]
Very much required

**Comment by zBritva** [comment]
Hello, @marcusdoesstuff @vipinmenontp.
The feature will available in next version. It's 1.4.3 or higher.
There is PR with changes: https://github.com/Microsoft/powerbi-visuals-sankey/commit/032505fd6ac8cf840c286cc2424b5adb2f6a9750
