### ISSUE TITLE
Microsoft Store Download

### ISSUE THREAD

**Issue by katwoodwsc** [microsoft/powerbi-visuals-sankey#184]
Unable to add from the store:

<img width="610" alt="Screenshot 2024-04-01 132809" src="https://github.com/microsoft/powerbi-visuals-sankey/assets/165331380/ce5336d5-8c49-48df-b053-5ac5635de6d2">

**Comment by MulyukovAidar** [comment]
Probably AppSource was down for a while, its not issue of the visual itself.
