### ISSUE TITLE
Sankey is not always refreshing in the July PowerBI Desktop Release

### ISSUE THREAD

**Issue by michpear** [microsoft/powerbi-visuals-sankey#20]
We've been using the Sankey for a few weeks now and its really great.  It seems that our team as well as other customers are having issues getting the Sankey to refresh after making a selection change in our slicers.  It seems to be totally random as to when it will update the Sankey after making a change in the Slicers.
Take a look at the reviews on the Office Store site.
https://store.office.com/en-us/app.aspx?assetid=WA104380777&ui=en-US&rs=en-US&ad=US&appredirect=false

**Comment by helen508light** [comment]
has already been resolved
