### ISSUE TITLE
Flow of the visual diagram is not as the data suggests

### ISSUE THREAD

**Issue by toddysm** [microsoft/powerbi-visuals-sankey#3]
We have the following data:
```
Source	Destination	Count
msftmfg	#cloud	        13
msftmfg	#security	        9
#security	peter	        6
#cloud	john	                3
```

However, the graphical representation is shown as in the picture.

![image](https://cloud.githubusercontent.com/assets/1007103/24314444/dfd8b5cc-109e-11e7-801a-91b871db7723.png)

Which is confusing. The problems we see are:

- `msftmfg` is never present in the Destination field yet the visual shows it as destination
- `peter` and `john` are never present in the Source field yet they are the sources in the visual

Our expectation is that the visual starts from `msftmfg` goes through `#security` and `#cloud` and ends with `peter` and `john`.

**Comment by zBritva** [comment]
Hello @toddysm, 

It looks that you confused field bucket.
I created a dataset with your samples and I got the same issue when changed source and destinations.

![image](https://user-images.githubusercontent.com/10897951/26965563-05a2a906-4cff-11e7-90dd-97c95047064d.png)

Could you check this issue again, please? 
Thank you for your feedback!
