### ISSUE TITLE
Show position of node as it's being dragged

### ISSUE THREAD

**Issue by dbruning** [Microsoft/powerbi-visuals-sankey#33]
Drag & drop is great but it's tricky to get the nodes lined up correctly if you can't see where it is until you drop it.

**Comment by zBritva** [comment]
@dbruning Thanks for the feedback. It's a known issue and it happens when you use words in source or destination with names starts numbers. The fix is going to publication.

**Comment by dbruning** [comment]
@zBritva Yes, works great now, thanks so much!
