### ISSUE TITLE
Add support for cycles

### ISSUE THREAD

**Issue by ryandle** [microsoft/powerbi-visuals-sankey#35]
Suppose your data set has a cycle, such as A->B and B->A. The current sankey visual will render it as:

![image](https://user-images.githubusercontent.com/578591/32062322-0900c2da-ba29-11e7-9abe-b3177256f17e.png)

But ideally the visual would not render the same node twice, but instead represent the cycle as another path between the nodes (perhaps with a different color, as done [here](https://bl.ocks.org/tomshanley/a23af553fabcb7a0d949b4d1a9b2b4fd).

The current behavior makes the visual pretty much unusable when you have cycles, as it is too confusing for users to deal with the same node being drawn multiple times.

**Comment by zBritva** [comment]
Hello @ryandle,

SankeyDiagram 1.7.1 was released. There is cycles support with backward links. You need to enable this feature on `Format panel`:

![image](https://user-images.githubusercontent.com/10897951/36779379-dda7dadc-1c80-11e8-80d3-dda58d25c382.png)

Your feedback will be very useful if you can provide a short review.

Thanks!

**Comment by helen508light** [comment]
has been resolved
