### ISSUE TITLE
Sankey diagram not fully visible

### ISSUE THREAD

**Issue by asigmund** [Microsoft/powerbi-visuals-sankey#61]
Hi,

in some cases the sankey diagram is not fully visible. Can you please check the attached screenshot. Is there any workaround for this problem?

Power BI Version 2.65.5313.701 64 Bit December 2018
Chart Version 1.10.0.0 Relaease Date 19.3.2017 (actual Version from store)

Best regards,

Alex

![sankey diagram](https://user-images.githubusercontent.com/4354697/50758607-f18aa100-1262-11e9-9fc5-35865458f636.jpg)

**Comment by zBritva** [comment]
Hello,

Can you share sample dataset without private data?

And could you check the visual version in Power BI, not in the appsource? Just the hover mouse on an icon of Sankey visual. 

Thanks!

**Comment by asigmund** [comment]
Hi,

actually when I tried to reproduce the error in a new Power BI worksheet the problem did not appear anymore. Even with the same data. I am now not able to reproduce the error. I deleted the broken chart and added a new one with the same configuration without any problems. Therefore I close the issue.

Thanks and regards,

Alex
