### ISSUE TITLE
Allow Measures for Source and Destination

### ISSUE THREAD

**Issue by jocooler** [microsoft/powerbi-visuals-sankey#63]
I have a date range filter and I want to see just two states for each item. In this case, I have projects and I want to see their start state and end state in any arbitrary period. I have a table with each project's status on each day. Start states are New or Carry Over and end states are Complete or Carry Over. I want to see flow for each path.

The way to show this start and end state would be through using a measure to find the first and last state for each item in the filtered date range, but measures can't be used in the source or destination fields.

Using measures for source and destination shouldn't have any ill effects for 2 state diagrams. Measures can't create a 3 state diagram anyway.

**Comment by helen508light** [comment]
> "Measures can't be used in the source or destination fields"
it is not in plans for now

May be Grouping change on GroupingOrMeasure will help you.
https://github.com/microsoft/powerbi-visuals-sankey/blob/master/capabilities.json#L5
I mean dataRoles "kind" type
