### ISSUE TITLE
Some aspects too small to show

### ISSUE THREAD

**Issue by marcusdoesstuff** [Microsoft/powerbi-visuals-sankey#8]
It would be nice to be able to force item labels to appear, even if the bar is very small.

You can also see below that some lines are too small to be visible. Perhaps an option to be able to specify a minimum width would be useful... Or a dotted line could be used when the line gets to a certain thinness. 

![capture4](https://user-images.githubusercontent.com/13677123/27431579-f84cec58-5744-11e7-8746-7db343726080.PNG)
(I've actually flipped my source and destination because it shows everything more clearly)

**Comment by zBritva** [comment]
@marcusdoesstuff
In the properties panel you can find option "Force display" at "Data labels" section. 
![image](https://user-images.githubusercontent.com/10897951/30685511-c9e1be8c-9ebd-11e7-90da-92c9ea519d2a.png)
If the property is switched on, the visual will display label in any case.
![image](https://user-images.githubusercontent.com/10897951/30685546-eb4f34aa-9ebd-11e7-86fd-dda7370c98f9.png)
