### ISSUE TITLE
Data privacy question

### ISSUE THREAD

**Issue by Coriroc** [microsoft/powerbi-visuals-sankey#82]
Hello! Thanks for making this, I love that you can drag the bars around! 

I had a quick question re. the following on the Microsoft app store. Apparently the app:
"Can send data over the Internet". After a quick skim through the code, I couldn't see anything obvious - what data can it send over the internet? It seems to be a general warning for everything but I was hoping for some clarity!

Thank you

**Comment by zBritva** [comment]
@Coriroc [Contact with support](https://docs.microsoft.com/en-us/power-bi/developer/visuals/power-bi-custom-visuals-faq#how-to-get-support)  to get details.

**Comment by Coriroc** [comment]
Thanks! Sorry to bother you
