### ISSUE TITLE
Tool-tip functionality

### ISSUE THREAD

**Issue by marcusdoesstuff** [Microsoft/powerbi-visuals-sankey#9]
Being able to add a tool-tip field (much like with the default charts) would be helpful.

For example, you might want to visualise the flow of value through a factory process, but also be able to hover over the bars to see the physical quantity of items used (some may be worth far more or less per unit).

**Comment by zBritva** [comment]
@marcusdoesstuff The feature was added. It will available on Monday

![image](https://user-images.githubusercontent.com/10897951/30684673-df0785ec-9eba-11e7-9187-140b164a02d6.png)
